[project]
name = "yeshivos-account-deletion"
version = "0.1.0"
description = "Add your description here"
requires-python = "==3.12.3"
dependencies = [
    "flask>=3.1.1",
    "gunicorn>=23.0.0",
    "python-dotenv>=1.1.1",
    "supabase>=2.16.0",
]
